### ISSUE TITLE
Missing client.coffee

### ISSUE THREAD

**Issue by montanaflynn** [sgentle/markov-technology#1]
It appears to have been replaced by [`client.coffee.md`](https://github.com/sgentle/markov-technology/blob/master/client.coffee.md). Very cool project, been jamming out to it!

**Comment by sgentle** [comment]
Hey thanks, I'm glad you're enjoying it!

Actually, `client.coffee.md` is the code. It's [literate Coffeescript](http://www.coffeescriptlove.com/2013/02/literate-coffeescript.html), so the non-code markdown blocks are just stripped out during compilation.

**Comment by montanaflynn** [comment]
That's very interesting. As someone who isn't familiar with coffeescript I had assumed it was a copy of the README.md. Great blog btw, I especially liked https://samgentle.com/posts/2016-04-30-participatory

**Comment by sgentle** [comment]
You were right, it is a copy of the README. In smaller projects I like to just symlink `README.md` to the `.coffee.md` as a kind of literate programming mic drop.

Thanks for reading it, I appreciate the kind words. :)
